name: Build PDF

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:
  
jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: docker://pandoc/latex:2.9
        with:
          args: README.md stellar_evolution_pseudocode.md --pdf-engine=xelatex --output=stellar_evolution_api.pdf
          
      - uses: actions/upload-artifact@v4
        with:
          name: stellar_evolution_api.pdf
          path: stellar_evolution_api.pdf
